version: "3"

volumes:
  rmq-data:
    driver: local

services:
  rabbitmq:
    build:
      context: .
      dockerfile: containers/rabbitmq/rabbitmq.dockerfile
      args:
        RABBITMQ_VERSION: ${RABBITMQ_VERSION:-3.13-management-alpine}
    image: links/rabbitmq:${RABBITMQ_VERSION:-3.13-management-alpine}
    container_name: ermes-broker
    hostname: ee05faa74f02
    ports:
      - 0.0.0.0:5671:5671
      - 127.0.0.1:15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER:-admin}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS:-admin}
      RABBITMQ_DEFAULT_VHOST: ${RABBITMQ_DEFAULT_VHOST:-/}
    volumes:
      - rmq-data:/var/lib/rabbitmq
    restart: unless-stopped
